@startuml Chat Sequence UML Diagram
autonumber 1.0.0
autoactivate on

queue "Message Broker" as MB
participant "Client" as C
participant "WebSocket Server" as WS
boundary "External Event Port" as EP
control "Group Handler" as GH
control "Group Actor" as GA
control "Client Actor" as CA

activate GH
activate EP

== Group Creation ==
MB -> EP: new group event
EP -> GH: create a new group
deactivate EP
GH -> GA **: spawn group entity
activate GA
deactivate GH

== New user join Group ==
autonumber inc B
MB -> EP: user join group event
EP -> GA: send user info to specific group
deactivate GA
GA -> CA **: spawn user entity
activate CA

== Client connection to the server ==
autonumber inc A
C -> WS: connect
WS -> GA: ask for user actor reference
alt user not found
    GA --> WS: return error
    WS --> C: return error
else user found
    GA -> GA: broadcast user connection event
    GA --> WS: return user actor reference
    WS --> C: return the URL used by client to connect to the server
end

== Send Message to group ==
autonumber inc A
C -> WS: send message to group
WS -> GA: send message
deactivate GA
GA -> GA: broadcast message to all users in the group
deactivate GA

== User leave group ==
autonumber inc A
C -> WS: disconnect
WS -> GA: send disconnection event
GA -> GA: remove user from the group
GA -> CA: destroy user entity
deactivate CA
destroy CA
deactivate GA
GA -> GA: broadcast user disconnection event
deactivate GA
@enduml