@startuml location-service

package infrastructure {

    package application {

        package domain {

            interface GPSPosition <<value object>> {
                + latitude: Double
                + longitude: Double
            }

'            interface Address <<value object>> {
'                + street: String
'                + city: String
'                + zip: String
'                + position: GPSPosition
'            }
'
'            Address *-r- "1" GPSPosition

            interface User <<entity>> {
                + id: UserId
                + inGroups: Set<GroupId>
            }
            interface UserId <<value object>>
            interface GroupId <<value object>>

            User *-u- "N" UserId
            User *-u- "N" GroupId

            interface Event {
                + timestamp: Date
                + user: User
            }

            User "1" --* Event

            interface StartRoutingEvent <<domain event>> extends Event {
                + arrivalPosition: GPSPosition
                + estimatedArrivalTime: Date
            }

            StartRoutingEvent *-- "1" GPSPosition

            interface TrackingEvent <<domain event>> extends Event {
                + position: GPSPosition
            }

            TrackingEvent *-- "1" GPSPosition

            interface StopRoutingEvent <<domain event>> extends Event

            interface SOSAlertEvent <<domain event>> extends Event {
                + position: GPSPosition
            }

            SOSAlertEvent *-- "1" GPSPosition
            
            interface Route <<aggregate root>> {
                + event: StartRoutingEvent
                + positions: List<TrackingEvent>
                + addTrace(TrackingEvent: TrackingEvent): Route
            }

            Route *-u- "1" StartRoutingEvent
            Route *-u- "N" TrackingEvent
        }

        interface TrackingEventsStore <<outbound port>> {
            + update(TrackingEvent: TrackingEvent)
            + by(user: User): TrackingEvent
        }

        TrackingEventsStore o.up. TrackingEvent

        interface RoutesStore <<outbound port>> {
            + update(Route: Route)
            + by(user: User): Route
            + delete(Route: Route)
        }

        RoutesStore o.up. Route

        interface NotificationsService <<outbound port>> {
            + notify(notificationEvent: NotificationEvent)
        }
        note left of NotificationsService::notify
            ""NotificationEvent"" is in 
            shared kernel module (?)
        end note

        NotificationsService o.. User

        interface MapsService <<outbound port>> {
            + estimateArrivalTime(start: GPSPosition, end: GPSPosition): Date
            + distance(start: GPSPosition, end: GPSPosition): GPSPosition
        }

        MapsService o.up. GPSPosition

        interface UserTrackingInfoService <<inbound port>> {
            + lastTraceOf(user: User): TrackingEvent
            + routeOf(user: User): Route
            + lastStateOf(user: User): State
        }
        note right of UserTrackingInfoService::routeOf
            At most 1 
            route per
            user per 
            time is active
        end note
        enum State {
            + ACTIVE,
            + INACTIVE,
            + SOS,
            + ROUTING
        }

        UserTrackingInfoService o.r. TrackingEvent
        UserTrackingInfoService o.r. State

        interface RoutesTrackingService <<outbound port>> {
            + onNewRoute()
            + onRoutingEvent()
        }
        RoutesTrackingService o.. Event

        interface RoutesInfoService <<inbound port>> {
            + routeOf(user: User): Route
        }
        RoutesInfoService o.u. Route

        interface RealTimeTrackingService <<inbound port>> {
            + onNewEvent(event: Event)
        }
        RealTimeTrackingService o.l. Event
    }

    class NotificationsServiceAdapter implements application.NotificationsService
    note top of NotificationsServiceAdapter
        This class is an adapter 
        that forwards notifications to 
        the notification microservice
        through message broker
    end note

    class MapsServiceAdapter <<outbound adapter>> implements application.MapsService
    note right of MapsServiceAdapter
        Uses external geocoding and maps APIs
    endnote

    class RealTimeTrackingKafkaAdapter <<inbound adapter>>
    RealTimeTrackingKafkaAdapter .up.> application.RealTimeTrackingService : <<uses>>

    class UserTrackingInfoGrpcAdapter <<inbound adapter>> 
    UserTrackingInfoGrpcAdapter .up.> application.UserTrackingInfoService : <<uses>>

    class RoutesTrackingServiceKafkaAdapter implements application.RoutesTrackingService

    class RoutesInfoGrpcAdapter
    RoutesInfoGrpcAdapter .up.> application.RoutesInfoService : <<uses>>

}

@enduml